<?php
session_start();
require '../../config/db.php';
header('Content-Type: application/json');

/* ================= AUTH ================= */
if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'super_admin') {
    http_response_code(403);
    echo json_encode(['success' => false, 'error' => 'Unauthorized']);
    exit;
}

/* ================= FILE CHECK ================= */
if (!isset($_FILES['file']) || $_FILES['file']['error'] !== UPLOAD_ERR_OK) {
    echo json_encode(['success' => false, 'error' => 'File upload failed']);
    exit;
}

$file = fopen($_FILES['file']['tmp_name'], 'r');

if (!$file) {
    echo json_encode(['success' => false, 'error' => 'Invalid file']);
    exit;
}

/* ================= READ HEADER ================= */
$header = fgetcsv($file);

// Normalize header (trim whitespace, lowercase, strip BOM) so minor
// formatting differences don't reject an otherwise valid file.
$normalizedHeader = array_map(function ($h) {
    return strtolower(trim($h, " \t\n\r\0\x0B\xEF\xBB\xBF"));
}, $header ?: []);

/*
 * FIX: added 'uom' to the expected header, matching the CSV template
 * generated by medicine_list.php's Download Template button (which was
 * already updated to include this column). Position matches the
 * template exactly: right after dosage.
 */
$expectedHeader = [
    'generic_name',
    'dosage',
    'uom',
    'duration',
    'signa',
    'description',
    'status'
];

if ($normalizedHeader !== $expectedHeader) {
    fclose($file);
    echo json_encode([
        'success' => false,
        'error' => 'Invalid CSV format. Please use the template file.'
    ]);
    exit;
}

/* ================= INIT ================= */
$inserted = 0;
$skipped  = 0;
$errors   = [];
$rowNum   = 1; // header was row 1

/* ================= PREPARE STATEMENTS ONCE ================= */
$checkStmt = $conn->prepare("
    SELECT COUNT(*) FROM medicines
    WHERE generic_name = ?
");

$insertStmt = $conn->prepare("
    INSERT INTO medicines (
        generic_name,
        dosage,
        uom,
        duration,
        signa,
        description,
        status
    ) VALUES (?,?,?,?,?,?,?)
");

/* ================= PROCESS ROWS ================= */
while (($row = fgetcsv($file)) !== false) {

    $rowNum++;

    try {
        // Skip fully blank rows (common at end of exported CSVs)
        if (count($row) === 1 && trim($row[0]) === '') {
            continue;
        }

        // FIX: column count updated from 6 to 7 to account for the new
        // uom column.
        if (count($row) < 7) {
            $skipped++;
            $errors[] = "Row {$rowNum}: expected 7 columns, got " . count($row);
            continue;
        }

        [
            $generic_name,
            $dosage,
            $uom,
            $duration,
            $signa,
            $description,
            $status
        ] = array_map('trim', $row);

        /* ================= VALIDATION ================= */
        if ($generic_name === '') {
            $skipped++;
            $errors[] = "Row {$rowNum}: missing generic name";
            continue;
        }

        // Normalize casing to match how the Add/Edit modal stores data
        $generic_name = strtoupper($generic_name);
        $uom          = $uom !== '' ? strtoupper($uom) : null;
        $signa        = $signa !== '' ? strtoupper($signa) : null;
        $description  = $description !== '' ? strtoupper($description) : null;

        $status = strtolower($status);
        if (!in_array($status, ['active', 'inactive'])) {
            $status = 'active';
        }

        /* ================= DUPLICATE CHECK ================= */
        $checkStmt->execute([$generic_name]);

        if ($checkStmt->fetchColumn() > 0) {
            $skipped++;
            $errors[] = "Row {$rowNum}: '{$generic_name}' already exists — skipped";
            continue;
        }

        /* ================= INSERT ================= */
        $insertStmt->execute([
            $generic_name,
            $dosage ?: null,
            $uom,
            $duration,
            $signa,
            $description,
            $status
        ]);

        $inserted++;

    } catch (Throwable $e) {
        $skipped++;
        $errors[] = "Row {$rowNum}: " . $e->getMessage();
    }
}

fclose($file);

/* ================= RESPONSE ================= */
echo json_encode([
    'success'  => true,
    'inserted' => $inserted,
    'skipped'  => $skipped,
    'message'  => "$inserted inserted, $skipped skipped",
    'errors'   => $errors
]);