<?php

header('Content-Type: application/json');

session_start();

require '../../config/db.php';

// Ensure PHP's own timestamp generation matches the rest of the app
// (view/patient.php already does this). This does NOT affect MySQL's
// NOW() — MySQL uses its own server timezone setting, which is why
// times were showing hours off even though PHP pages displayed
// correctly. Fix: generate all timestamps in PHP and pass them in
// explicitly instead of letting MySQL's NOW() run.
date_default_timezone_set('Asia/Manila');


/*
|--------------------------------------------------------------------------
| AUTHENTICATION
|--------------------------------------------------------------------------
*/

if (!isset($_SESSION['user'])) {

    echo json_encode([
        'status'=>'error',
        'message'=>'Unauthorized access'
    ]);

    exit;
}


$user = $_SESSION['user'];

$user_id     = $user['id'];
$user_role   = $user['role'];
$facility_id = $user['facility_id'] ?? null;



/*
|--------------------------------------------------------------------------
| INPUT
|--------------------------------------------------------------------------
*/

$patient_id = intval($_POST['patient_id'] ?? 0);

$diagnosis = trim($_POST['diagnosis'] ?? '');

$remarks = trim($_POST['remarks'] ?? '');


$is_refill = strtoupper(
    $_POST['is_refill'] ?? 'NO'
);



$med_names = $_POST['medicine_name'] ?? [];
$dosages   = $_POST['dosage'] ?? [];
$freqs     = $_POST['frequency'] ?? [];
$durations = $_POST['duration'] ?? [];
$qtys      = $_POST['quantity'] ?? [];
$notes     = $_POST['notes'] ?? [];




/*
|--------------------------------------------------------------------------
| VALIDATION
|--------------------------------------------------------------------------
*/


if(!$patient_id){

    echo json_encode([
        'status'=>'error',
        'message'=>'Patient is required.'
    ]);

    exit;
}



if(!$is_refill || !in_array($is_refill,['YES','NO'])){

    $is_refill='NO';

}



if(empty($med_names)){

    echo json_encode([
        'status'=>'error',
        'message'=>'At least one medicine is required.'
    ]);

    exit;
}





foreach($med_names as $i=>$medicine){


    $medicine = trim($medicine);


    if(empty($medicine)){

        echo json_encode([
            'status'=>'error',
            'message'=>'Medicine name cannot be empty.'
        ]);

        exit;

    }



    $duration = intval($durations[$i] ?? 0);

    $quantity = intval($qtys[$i] ?? 0);



    if($duration <= 0){

        echo json_encode([
            'status'=>'error',
            'message'=>'Duration must be greater than zero.'
        ]);

        exit;

    }



    if($quantity <= 0){

        echo json_encode([
            'status'=>'error',
            'message'=>'Quantity must be greater than zero.'
        ]);

        exit;

    }


}



/*
|--------------------------------------------------------------------------
| CURRENT TIMESTAMP (Asia/Manila, generated by PHP)
|--------------------------------------------------------------------------
|
| Used everywhere below INSTEAD OF MySQL's NOW() so the stored value
| always matches the timezone the app displays in — regardless of
| what timezone the MySQL server itself is configured with.
|--------------------------------------------------------------------------
*/

$now = date('Y-m-d H:i:s');




try{


$conn->beginTransaction();



/*
|--------------------------------------------------------------------------
| GENERATE PRESCRIPTION NUMBER
|--------------------------------------------------------------------------
|
| Reads the last issued number for today and increments it, locking
| the row with FOR UPDATE so concurrent submissions can't read the
| same "last number" and collide (see previous fix).
|--------------------------------------------------------------------------
*/


$date = date('Ymd');


$stmt = $conn->prepare("
    SELECT prescription_number
    FROM prescriptions
    WHERE prescription_number LIKE ?
    ORDER BY id DESC
    LIMIT 1
    FOR UPDATE
");

$stmt->execute(["RX-{$date}-%"]);

$lastNumber = $stmt->fetchColumn();

if ($lastNumber) {
    $lastSeq = (int) substr($lastNumber, strrpos($lastNumber, '-') + 1);
    $nextSeq = $lastSeq + 1;
} else {
    $nextSeq = 1;
}

$rx_number =
"RX-".$date."-".str_pad($nextSeq,3,'0',STR_PAD_LEFT);





/*
|--------------------------------------------------------------------------
| SIGNATURE / ROLE PROCESS
|--------------------------------------------------------------------------
*/


$status = 'For Signing';

$doctor_id = null;

$signed_at = null;

$signature_path = null;



if($user_role === 'doctor'){


    $doctor_id = $user_id;



    $stmt = $conn->prepare("
        SELECT signature_path
        FROM users
        WHERE id=?
        LIMIT 1
    ");


    $stmt->execute([
        $user_id
    ]);


    $doctor = $stmt->fetch(PDO::FETCH_ASSOC);



    if(!$doctor || empty($doctor['signature_path'])){


        throw new Exception(
            "Doctor signature is missing."
        );

    }



    $status='Signed';

    $signed_at=$now;

    $signature_path=$doctor['signature_path'];

}





/*
|--------------------------------------------------------------------------
| INSERT PRESCRIPTION
|--------------------------------------------------------------------------
*/


$stmt = $conn->prepare("

INSERT INTO prescriptions
(
prescription_number,
patient_id,
created_by,
doctor_id,
facility_id,
diagnosis,
remarks,
is_refill,
status,
signed_at,
signature_path,
created_at
)

VALUES
(
?,?,?,?,?,?,?,?,?,?,?,?
)

");



$stmt->execute([

$rx_number,

$patient_id,

$user_id,

$doctor_id,

$facility_id,

$diagnosis,

$remarks,

$is_refill,

$status,

$signed_at,

$signature_path,

$now

]);



$prescription_id=$conn->lastInsertId();





/*
|--------------------------------------------------------------------------
| INSERT MEDICINES
|--------------------------------------------------------------------------
*/


$stmtMed=$conn->prepare("

INSERT INTO prescription_medicines
(
prescription_id,
medicine_name,
dosage,
frequency,
duration,
quantity,
notes,
status,
created_at
)

VALUES
(
?,?,?,?,?,?,?,
'Pending',
?
)

");




foreach($med_names as $i=>$medicine){


$stmtMed->execute([

$prescription_id,

trim($medicine),

trim($dosages[$i] ?? ''),

trim($freqs[$i] ?? ''),

intval($durations[$i]),

intval($qtys[$i]),

trim($notes[$i] ?? ''),

$now

]);


}






/*
|--------------------------------------------------------------------------
| UPDATE PATIENT DATES
|--------------------------------------------------------------------------
|
| LAST PRESCRIPTION DATE:
| - Always update
| - Includes refill
|
| LAST MEDICAL CONSULT:
| - ONLY real consultation
| - Refill does NOT update
|
|--------------------------------------------------------------------------
*/


$stmt = $conn->prepare("

UPDATE patients

SET last_prescription_date = ?

WHERE id=?

");


$stmt->execute([
    $now,
    $patient_id
]);





if($is_refill === 'NO'){


    $stmt = $conn->prepare("

    UPDATE patients

    SET last_medical_consult = ?

    WHERE id=?

    ");


    $stmt->execute([
        $now,
        $patient_id
    ]);


}





$conn->commit();




echo json_encode([

'status'=>'success',

'message'=>

$user_role === 'doctor'

?

'Prescription signed successfully.'

:

'Prescription submitted for doctor signing.',


'rx'=>$rx_number,


'is_refill'=>$is_refill

]);





}catch(Exception $e){



if($conn->inTransaction()){

    $conn->rollBack();

}



echo json_encode([

'status'=>'error',

'message'=>$e->getMessage()

]);


}

?>