<?php
session_start();
require '../../config/db.php';
require '../../includes/ClientPrescriptionApi.php';

header('Content-Type: application/json');

/*
|--------------------------------------------------------------------------
| TIMEZONE FIX
|--------------------------------------------------------------------------
| Same issue as prescription_process.php: MySQL's NOW() runs on the DB
| server's own clock (commonly UTC), not the app's local timezone. All
| timestamps here are now generated in PHP with Asia/Manila explicitly
| set, then passed in as bound parameters.
|--------------------------------------------------------------------------
*/
date_default_timezone_set('Asia/Manila');

// ================= HELPERS =================
function response($data = [], $status = 200) {
    http_response_code($status);
    echo json_encode($data);
    exit;
}

function requireFacilityAuth() {
    if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'health_facility') {
        response(['error' => 'Unauthorized'], 401);
    }
    return $_SESSION['user'];
}

/*
 * FIX: new for the centralized (cross-facility) transmittal view.
 * requireFacilityAuth() above hard-blocks anyone who isn't
 * health_facility — calling it unconditionally (as this file used to)
 * meant a new action for pharmacy/super_admin could never be reached at
 * all. This is a SEPARATE auth path used only by action=list_centralized,
 * so the original health_facility-only actions (list, get_prescriptions,
 * generate) are completely untouched and still behave exactly as before.
 */
function requireCentralizedAuth() {
    if (!isset($_SESSION['user']) || !in_array($_SESSION['user']['role'], ['pharmacy', 'super_admin'], true)) {
        response(['error' => 'Unauthorized'], 401);
    }
    return $_SESSION['user'];
}

function getFacilityName($conn, $id) {
    $stmt = $conn->prepare("SELECT facility_name FROM health_facilities WHERE id = ?");
    $stmt->execute([$id]);
    return $stmt->fetchColumn();
}

/*
 * FIX: $action is now read BEFORE deciding which auth function to run,
 * so the centralized action can take its own auth path instead of being
 * forced through requireFacilityAuth() first (which would reject it).
 * Every action this file had BEFORE this change still goes through
 * requireFacilityAuth() exactly as before — only the new
 * list_centralized branch is different.
 */
$action = $_REQUEST['action'] ?? '';

if ($action === 'list_centralized') {
    $user = requireCentralizedAuth();
} else {
    $user = requireFacilityAuth();
}

$facilityId = $user['facility_id'] ?? null;
$sessionPharmacyId = $user['pharmacy_id'] ?? null;

/* ================= GENERATED BY ================= */

function getGeneratedBy($conn, $userId)
{
    $stmt = $conn->prepare("
        SELECT CONCAT(first_name,' ',last_name)
        FROM users
        WHERE id = ?
        LIMIT 1
    ");

    $stmt->execute([$userId]);

    $name = $stmt->fetchColumn();

    return $name ?: 'Unknown User';
}


$generatedBy = getGeneratedBy(
    $conn,
    $user['id']
);

// ================= ROUTER =================
switch ($action) {

    /* ================= LIST (single-facility — health_facility only) ================= */
    case 'list':
        try {
            // Optional date filter (matches the "Filter by Date" search box
            // added on the transmittal list page). Filters on date_generated.
            $filterDate = $_GET['date'] ?? null;

            $sql = "
                SELECT
                    id,
                    date_generated,
                    prescription_date,
                    delivery_date,
                    num_patients,
                    status,
                    health_facility,
                    pharmacist,
                    generated_by,
                    transmitted
                FROM transmittals
                WHERE facility_id = ?
            ";

            $params = [$facilityId];

            if ($filterDate) {
                $sql .= " AND DATE(date_generated) = ? ";
                $params[] = $filterDate;
            }

            $sql .= " ORDER BY id DESC ";

            $stmt = $conn->prepare($sql);
            $stmt->execute($params);

            response([
                'status' => 'success',
                'data' => $stmt->fetchAll(PDO::FETCH_ASSOC)
            ]);

        } catch (Exception $e) {
            response(['error' => $e->getMessage()], 500);
        }
        break;

    /* ================= LIST CENTRALIZED (pharmacy / super_admin — cross-facility) ================= */
    /*
     * NEW: the ONLY place in this file where a transmittal list can be
     * filtered by Pharmacy or Facility, since it's the only one that
     * isn't already hard-scoped to a single facility. `list` above
     * can't support this filter at all — it's already restricted to
     * exactly one facility_id (the session's own), so there's nothing
     * to filter ACROSS.
     *
     * Scoping:
     *   - super_admin: sees everything; may optionally filter by any
     *     pharmacy_id and/or facility_id.
     *   - pharmacy: always scoped to their OWN pharmacy_id (never
     *     accepts a different pharmacy_id from the client — a pharmacy
     *     account can only ever see transmittals for facilities under
     *     its own pharmacy), but may still narrow further by a specific
     *     facility_id within that scope.
     */
    case 'list_centralized':
        try {
            $filterDate = $_GET['date'] ?? null;
            $filterFacilityId = $_GET['facility_id'] ?? null;

            // Pharmacy accounts can never widen their own scope — their
            // own pharmacy_id always wins over anything the client sends.
            $filterPharmacyId = ($user['role'] === 'pharmacy')
                ? $sessionPharmacyId
                : ($_GET['pharmacy_id'] ?? null);

            $sql = "
                SELECT
                    t.id,
                    t.date_generated,
                    t.prescription_date,
                    t.delivery_date,
                    t.num_patients,
                    t.status,
                    t.health_facility,
                    t.pharmacist,
                    t.generated_by,
                    t.transmitted,
                    t.facility_id,
                    hf.pharmacy_id,
                    p.pharmacy_name
                FROM transmittals t
                LEFT JOIN health_facilities hf ON t.facility_id = hf.id
                LEFT JOIN pharmacy p ON hf.pharmacy_id = p.id
                WHERE 1 = 1
            ";
            $params = [];

            if ($filterPharmacyId) {
                $sql .= " AND hf.pharmacy_id = ? ";
                $params[] = $filterPharmacyId;
            }

            if ($filterFacilityId) {
                $sql .= " AND t.facility_id = ? ";
                $params[] = $filterFacilityId;
            }

            if ($filterDate) {
                $sql .= " AND DATE(t.date_generated) = ? ";
                $params[] = $filterDate;
            }

            $sql .= " ORDER BY t.id DESC ";

            $stmt = $conn->prepare($sql);
            $stmt->execute($params);

            response([
                'status' => 'success',
                'data' => $stmt->fetchAll(PDO::FETCH_ASSOC)
            ]);

        } catch (Exception $e) {
            response(['error' => $e->getMessage()], 500);
        }
        break;

    /* ================= GET PRESCRIPTIONS ================= */
    case 'get_prescriptions':

        $presDate = $_GET['pres_date'] ?? null;

        // Status is intentionally hardcoded server-side to "Signed" too —
        // even if a caller sends a different value, only signed
        // prescriptions are ever eligible for transmittal. This mirrors
        // the frontend lock (status is no longer a user-editable field).
        $status = 'Signed';

        if (!$presDate) {
            response(['error' => 'Missing parameters'], 422);
        }

        try {
            /*
             * FIX (not-yet-transmitted guarantee, part 1 of 2 — the
             * other half is in the `generate` action below): only ever
             * list prescriptions that haven't been attached to a
             * transmittal yet.
             *
             * Checks for NULL OR 0 OR empty string, not just NULL —
             * defensive against any legacy rows where transmittal_id may
             * have been left at a default of 0 or '' rather than a true
             * NULL (common when a nullable column gets added to an
             * existing table without every old row being explicitly
             * NULLed out). Remove the extra OR conditions if you've
             * confirmed transmittal_id is always genuinely NULL until
             * set.
             */
            $stmt = $conn->prepare("
                SELECT 
                    p.id,
                    p.prescription_number,
                    p.diagnosis,
                    CONCAT(pt.first_name,' ',pt.last_name) AS patient_name
                FROM prescriptions p
                JOIN patients pt ON pt.id = p.patient_id
                WHERE 
                    p.facility_id = ?
                    AND DATE(p.created_at) = ?
                    AND p.status = ?
                    AND (p.transmittal_id IS NULL OR p.transmittal_id = 0 OR p.transmittal_id = '')
                ORDER BY p.id DESC
            ");

            $stmt->execute([$facilityId, $presDate, $status]);

            response([
                'status' => 'success',
                'data' => $stmt->fetchAll(PDO::FETCH_ASSOC)
            ]);

        } catch (Exception $e) {
            response(['error' => $e->getMessage()], 500);
        }
        break;

    /* ================= GENERATE ================= */
    case 'generate':

        $transDate    = $_POST['trans_date'] ?? null;
        $presDate     = $_POST['pres_date'] ?? null;
        $deliveryDate = $_POST['delivery_date'] ?? null; // optional
        $pharmacy     = $_POST['pharmacy'] ?? null;
        $presList     = $_POST['prescriptions'] ?? [];

        // Status is locked to "Signed" server-side as well — not accepted
        // from the client as a variable value.
        $status = 'Signed';

        if (!$transDate || !$presDate || !$pharmacy || empty($presList)) {
            response(['error' => 'Missing required fields'], 422);
        }

        // Normalize optional delivery date: empty string / "null" -> NULL
        if ($deliveryDate === '' || $deliveryDate === 'null') {
            $deliveryDate = null;
        }

        try {
            $conn->beginTransaction();

            // App-local "now" (Asia/Manila) — used instead of MySQL's NOW()
            // so stored times match when the action actually happened.
            $nowDateTime = date('Y-m-d H:i:s');

            /*
             * ITEM 5.1 FIX: date_generated must reflect the actual moment
             * the transmittal was generated (date AND time), matching the
             * renamed "Date and Time Generated" column on the list page.
             *
             * Previously this was bound to $transDate — the value of the
             * modal's "Date *" <input type="date">, which is a date-only
             * field with no time component. Since HTML date inputs report
             * midnight for any time portion, every transmittal's
             * date_generated ended up stored as e.g. "2026-08-12 00:00:00"
             * regardless of what time it was actually generated.
             *
             * $nowDateTime (already computed above, Asia/Manila-aware) is
             * the real current timestamp — same source already used for
             * transmitted_at below — so that's what date_generated should
             * use instead. $transDate is still required/validated as
             * before in case anything downstream relies on its presence,
             * but it's no longer written into date_generated.
             */
            // Insert transmittal
            $stmt = $conn->prepare("
                INSERT INTO transmittals
                (date_generated, prescription_date, delivery_date, health_facility, pharmacist, status, num_patients, generated_by, facility_id)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ");

            $stmt->execute([
                $nowDateTime,
                $presDate,
                $deliveryDate,
                getFacilityName($conn, $facilityId),
                $pharmacy,
                $status,
                count($presList),
                $generatedBy,
                $facilityId
            ]);

            $transId = $conn->lastInsertId();

            // Prepare reusable statements (performance)
            $insertTP = $conn->prepare("
                INSERT INTO transmittal_prescriptions (transmittal_id, prescription_id)
                VALUES (?, ?)
            ");

            /*
             * FIX (not-yet-transmitted guarantee, part 2 of 2): this
             * UPDATE only claims a prescription if it's STILL untransmitted
             * at this exact moment — the WHERE clause re-checks
             * transmittal_id right here, inside this transaction, rather
             * than trusting that whatever was shown in the "eligible
             * prescriptions" list moments ago is still accurate.
             *
             * Why this matters: the list the user searched is a snapshot
             * from an earlier request. Between that search and clicking
             * Generate, another staff member (or another browser tab)
             * could have already transmitted the same prescription. The
             * list-time filter in get_prescriptions alone can't prevent
             * that — only re-checking at the moment of actually writing
             * transmittal_id can. If rowCount() comes back 0 for a given
             * prescription, it means someone else claimed it first in
             * that window, so it's skipped here (not inserted into
             * transmittal_prescriptions, not double-counted) and reported
             * back to the frontend as skipped rather than silently
             * pretending it was included.
             */
            $updatePres = $conn->prepare("
                UPDATE prescriptions 
                SET transmittal_id = ?,
                    transmitted_at = ?
                WHERE id = ?
                  AND (transmittal_id IS NULL OR transmittal_id = 0 OR transmittal_id = '')
            ");

            $claimedIds = [];
            $alreadyTransmittedIds = [];

            foreach ($presList as $pid) {
                $updatePres->execute([$transId, $nowDateTime, $pid]);

                if ($updatePres->rowCount() > 0) {
                    // Successfully claimed — safe to record on this transmittal.
                    $insertTP->execute([$transId, $pid]);
                    $claimedIds[] = $pid;
                } else {
                    // Someone else already transmitted this one first.
                    $alreadyTransmittedIds[] = $pid;
                }
            }

            // The transmittal's own num_patients count (written above at
            // INSERT time) assumed every requested prescription would be
            // claimed. If any were skipped due to the race above, correct
            // it to the real count so the transmittal list/PDF don't
            // overstate how many patients are actually on it.
            if (count($alreadyTransmittedIds) > 0) {
                $fixCount = $conn->prepare("UPDATE transmittals SET num_patients = ? WHERE id = ?");
                $fixCount->execute([count($claimedIds), $transId]);
            }

            $conn->commit();

            // ================= SYNC TO CLIENT API =================
            // Done AFTER the internal DB commit, on purpose: the
            // transmittal is considered generated locally regardless of
            // whether the client's Business Central system is reachable
            // right now. We don't want a slow/unreachable external API
            // holding a DB transaction open, or blocking staff from
            // generating transmittals when the client's server is down.
            //
            // Any failures are collected and returned to the frontend so
            // the user can see which prescriptions still need to be
            // resent, rather than failing the whole request silently.
            $clientApi = new ClientPrescriptionApi($conn);
            $syncResults = [];
            $syncFailures = [];

            // Only sync prescriptions actually claimed by THIS transmittal —
            // $claimedIds, not the original $presList, since anything in
            // $alreadyTransmittedIds was skipped above and doesn't belong
            // to this transmittal at all.
            foreach ($claimedIds as $pid) {
                $result = $clientApi->sendPrescription((int)$pid);
                $syncResults[] = $result;
                if (!$result['success']) {
                    $syncFailures[] = $result;
                }
            }

            response([
                'status' => 'success',
                'message' => count($alreadyTransmittedIds) > 0
                    ? 'Transmittal generated, but ' . count($alreadyTransmittedIds) . ' prescription(s) were already transmitted by someone else in the meantime and were skipped.'
                    : 'Transmittal generated successfully',
                'transmittal_id' => $transId,
                'skipped_already_transmitted' => $alreadyTransmittedIds,
                'client_sync' => [
                    'total' => count($syncResults),
                    'failed' => count($syncFailures),
                    'failures' => $syncFailures,
                ],
            ]);

        } catch (Exception $e) {
            $conn->rollBack();
            response(['error' => $e->getMessage()], 500);
        }
        break;

    /* ================= DEFAULT ================= */
    default:
        response(['error' => 'Invalid action'], 400);
}